# Generated by tools/make_el_dorado.py; edit the shapes there, not here.
extends RefCounted

const WALLS := [
	[Vector2(0, 0), Vector2(720, 0), Vector2(720, 300), Vector2(656, 300), Vector2(646, 232), Vector2(618, 170), Vector2(572, 118), Vector2(508, 82), Vector2(436, 63), Vector2(360, 58), Vector2(284, 63), Vector2(212, 82), Vector2(148, 118), Vector2(102, 170), Vector2(74, 232), Vector2(64, 300), Vector2(0, 300)],
	[Vector2(0, 290), Vector2(64, 290), Vector2(64, 880), Vector2(130, 1000), Vector2(121, 1003), Vector2(121, 1123), Vector2(117, 1163), Vector2(174, 1210), Vector2(278, 1264), Vector2(279, 1282), Vector2(0, 1282)],
	[Vector2(720, 290), Vector2(656, 290), Vector2(656, 880), Vector2(547, 999), Vector2(556, 1003), Vector2(557, 1112), Vector2(564, 1162), Vector2(486, 1219), Vector2(396, 1264), Vector2(397, 1282), Vector2(720, 1282)],
	[Vector2(122, 1003), Vector2(130, 1000), Vector2(140, 1005), Vector2(142, 1083), Vector2(144, 1092), Vector2(157, 1105), Vector2(181, 1121), Vector2(254, 1167), Vector2(240, 1172), Vector2(238, 1186), Vector2(242, 1200), Vector2(231, 1198), Vector2(217, 1189), Vector2(142, 1139), Vector2(126, 1128), Vector2(121, 1123), Vector2(121, 1116)],
	[Vector2(537, 1005), Vector2(547, 999), Vector2(555, 1003), Vector2(556, 1047), Vector2(557, 1112), Vector2(553, 1122), Vector2(491, 1165), Vector2(453, 1189), Vector2(442, 1199), Vector2(440, 1186), Vector2(436, 1173), Vector2(421, 1169), Vector2(428, 1167), Vector2(472, 1137), Vector2(534, 1092)],
	[Vector2(189, 1002), Vector2(184, 1008), Vector2(185, 1064), Vector2(238, 1098), Vector2(248, 1094), Vector2(249, 1083), Vector2(197, 1003)],
	[Vector2(482, 1004), Vector2(426, 1085), Vector2(427, 1094), Vector2(433, 1099), Vector2(444, 1098), Vector2(490, 1068), Vector2(492, 1007), Vector2(488, 1001)],
	[Vector2(242, 1188), Vector2(226, 1188), Vector2(190, 1214), Vector2(196, 1219), Vector2(234, 1238), Vector2(246, 1210)],
	[Vector2(440, 1188), Vector2(456, 1188), Vector2(492, 1214), Vector2(486, 1219), Vector2(448, 1238), Vector2(436, 1210)],
]
const KING_Y := 250
const KING_X := Vector2(220, 500)  # the two ends of his path
const COINS := [Vector2(200, 560), Vector2(520, 560), Vector2(360, 470)]
const COIN_RADIUS := 24
const ENTRY := Vector2(360, 380)
const DRAIN_AT := Vector2(336, 1272)
const DRAIN_SIZE := Vector2(115, 20)
