# Generated by tools/make_el_dorado.py; edit the shapes there, not here.
extends RefCounted

const WALLS := [
	[Vector2(0, 0), Vector2(720, 0), Vector2(720, 300), Vector2(656, 300), Vector2(646, 232), Vector2(618, 170), Vector2(572, 118), Vector2(508, 82), Vector2(436, 63), Vector2(360, 58), Vector2(284, 63), Vector2(212, 82), Vector2(148, 118), Vector2(102, 170), Vector2(74, 232), Vector2(64, 300), Vector2(0, 300)],
	[Vector2(0, 290), Vector2(64, 290), Vector2(64, 880), Vector2(149, 1000), Vector2(140, 1003), Vector2(140, 1123), Vector2(136, 1163), Vector2(193, 1210), Vector2(297, 1264), Vector2(298, 1282), Vector2(0, 1282)],
	[Vector2(720, 1282), Vector2(422, 1282), Vector2(423, 1264), Vector2(527, 1210), Vector2(584, 1163), Vector2(580, 1123), Vector2(580, 1003), Vector2(571, 1000), Vector2(656, 880), Vector2(656, 290), Vector2(720, 290)],
	[Vector2(141, 1003), Vector2(149, 1000), Vector2(159, 1005), Vector2(161, 1083), Vector2(163, 1092), Vector2(176, 1105), Vector2(200, 1121), Vector2(273, 1167), Vector2(259, 1172), Vector2(257, 1186), Vector2(261, 1200), Vector2(250, 1198), Vector2(236, 1189), Vector2(161, 1139), Vector2(145, 1128), Vector2(140, 1123), Vector2(140, 1116)],
	[Vector2(580, 1116), Vector2(580, 1123), Vector2(575, 1128), Vector2(559, 1139), Vector2(484, 1189), Vector2(470, 1198), Vector2(459, 1200), Vector2(463, 1186), Vector2(461, 1172), Vector2(447, 1167), Vector2(520, 1121), Vector2(544, 1105), Vector2(557, 1092), Vector2(559, 1083), Vector2(561, 1005), Vector2(571, 1000), Vector2(579, 1003)],
	[Vector2(208, 1002), Vector2(203, 1008), Vector2(204, 1064), Vector2(257, 1098), Vector2(267, 1094), Vector2(268, 1083), Vector2(216, 1003)],
	[Vector2(504, 1003), Vector2(452, 1083), Vector2(453, 1094), Vector2(463, 1098), Vector2(516, 1064), Vector2(517, 1008), Vector2(512, 1002)],
	[Vector2(261, 1188), Vector2(245, 1188), Vector2(209, 1214), Vector2(215, 1219), Vector2(253, 1238), Vector2(265, 1210)],
	[Vector2(455, 1210), Vector2(467, 1238), Vector2(505, 1219), Vector2(511, 1214), Vector2(475, 1188), Vector2(459, 1188)],
]
const KING_Y := 250
const KING_X := Vector2(220, 500)  # the two ends of his path
const COINS := [Vector2(200, 560), Vector2(520, 560), Vector2(360, 470)]
const COIN_RADIUS := 24
const ENTRY := Vector2(360, 380)
const DRAIN_AT := Vector2(360, 1272)
const DRAIN_SIZE := Vector2(115, 20)
const SHIFT := 19  # the table's flipper area, moved to the chamber's centre line
const CENTRE := 360
