"""The left orbit's guide line (Scripts/orbit_geometry.gd), for Scripts/orbit_guide.gd.

A fast ball running along the left orbit's outer wall - round over the top from the
launch side and down the left lane, or up the lane (the torch lane) and round the other
way - is carried along this line, a ball's radius in from the wall, rather than left to
the physics: a ball skidding round a tight curve of straight wall pieces hitches as it
taps from one to the next. Drawn from the same sweep and arc the wall's collider in
node_2d.tscn follows. Run from the repo root:  python3 tools/make_orbit_path.py
"""
import math

BALL = 19.5      # the ball's radius, and a hair: the line keeps it just off the wall
OUT = "Scripts/orbit_geometry.gd"


def cr(p0, p1, p2, p3, t):
    return tuple(0.5 * ((2 * p1[i]) + (-p0[i] + p2[i]) * t + (2 * p0[i] - 5 * p1[i] + 4 * p2[i] - p3[i]) * t * t
                        + (-p0[i] + 3 * p1[i] - 3 * p2[i] + p3[i]) * t ** 3) for i in range(2))


def wall():
    """The orbit's outer wall, as the colliders have it (scene units), from the top run across
    from the launch side, round, and down the left lane."""
    chain = [(410.0, 205.0), (370.0, 200.8)]  # the launch orbit's wall coming across the top
    ctrl = [(336, 196), (300, 193), (268, 199), (236, 208), (206, 220), (178, 233), (152, 247), (127, 262), (104, 278)]
    phi0 = math.radians(38)
    ext = [chain[-1]] + ctrl + [(104 - 30 * math.cos(phi0), 278 + 30 * math.sin(phi0))]
    for k in range(1, len(ext) - 2):
        for j in range(8):
            chain.append(cr(ext[k - 1], ext[k], ext[k + 1], ext[k + 2], j / 8))
    radius = 191.0  # the even arc down into the lane
    for deg in range(38, 87, 2):
        phi = math.radians(deg)
        chain.append((104 - radius * (math.sin(phi) - math.sin(phi0)), 278 + radius * (math.cos(phi0) - math.cos(phi))))
    # down the lane, and on past where its wall meets the one below (CollisionPolygon2D7's edge
    # from (44, 706) to (87, 802)) at an angle, so the ball isn't knocked there either
    chain += [(31.5, 470), (32, 560), (32, 611), (40.8, 671), (46, 703), (55, 724), (70, 758), (87, 802), (96, 822)]
    return chain


def chaikin(chain, rounds):
    for _ in range(rounds):
        out = [chain[0]]
        for a, b in zip(chain, chain[1:]):
            out.append((0.75 * a[0] + 0.25 * b[0], 0.75 * a[1] + 0.25 * b[1]))
            out.append((0.25 * a[0] + 0.75 * b[0], 0.25 * a[1] + 0.75 * b[1]))
        out.append(chain[-1])
        chain = out
    return chain


def main():
    w = chaikin(wall(), 2)
    line = []
    for k, q in enumerate(w):
        a, b = w[max(k - 1, 0)], w[min(k + 1, len(w) - 1)]
        tx, ty = b[0] - a[0], b[1] - a[1]
        ln = math.hypot(tx, ty) or 1.0
        line.append((q[0] + ty / ln * BALL, q[1] - tx / ln * BALL))  # in from the wall, toward the playfield
    line = chaikin(line, 1)
    kept = [line[0]]
    for q in line[1:]:
        if math.dist(q, kept[-1]) >= 4.0:
            kept.append(q)
    lines = ["## The left orbit's guide line, a ball's radius in from its outer wall: from the top run",
             "## across from the launch side, round, and down the left lane to its foot (scene units).",
             "## Generated by tools/make_orbit_path.py: edit that and re-run it rather than this.",
             "const PATH := ["]
    lines += ["\tVector2(%.1f, %.1f)," % q for q in kept]
    lines += ["]", ""]
    open(OUT, "w", newline="\n").write("\n".join(lines))
    print("wrote", OUT, len(kept), "points")


if __name__ == "__main__":
    main()
